- repo: git://github.com/pre-commit/mirrors-yapf
  sha: v0.17.0
  hooks:
  - id: yapf
    language: system

- repo: local
  hooks:
  - id: travis-linter
    name: travis
    entry: travis lint
    files: .travis.yml
    language: ruby
    additional_dependencies: ['travis']
