language: python
python: 
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - rabbitmq-server
      - gfortran
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo service postgresql restart
install:
  - pip install .[test,dev,docs]
  - reentry scan
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  # I make sure that I can import the module without the need of having the AiiDA environment/profile loaded
  - python -c "import aiida_wannier90"
  # I run all other tests
  - ./.travis-data/test_script.sh
