language: python
python: 
  - "2.7"
  - "3.6"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - rabbitmq-server
      - gfortran
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo service postgresql restart
install:
  - pip install git+https://github.com/aiidateam/aiida_core.git@develop#egg=aiida_core
  - pip install git+https://github.com/greschd/aiida_pytest@migrate_v1#egg=aiida_pytest
  - pip install .[test,dev,docs]
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
