language: python
python: 
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - rabbitmq-server
      - gfortran
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo service postgresql restart
install:
  - pip install .[test,dev,docs]
  - reentry scan
env:
  # The variable READTHEDOCS=True is used to emulate what happens on
  # ReadTheDocs for what concerns compilation of the docs (see logic inside
  # docs/source/conf.py)
  - TEST_TYPE="pre-commit" READTHEDOCS=True
  - TEST_TYPE="tests"

script:
  - ./.travis-data/test_script.sh
