language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - rabbitmq-server
before_install:
  - sudo service postgresql restart
env:
  - INSTALL_TYPE="docs" TEST_TYPE="docs"
  - INSTALL_TYPE="dev_precommit" TEST_TYPE="pre-commit"
  - INSTALL_TYPE="testing" TEST_TYPE="tests"
  - INSTALL_TYPE="testing_sdist" TEST_TYPE="tests"
install:
  - ./.travis-data/install_script.sh
script:
  - ./.travis-data/test_script.sh
