language: python
python: 
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - rabbitmq-server
      - gfortran
      - libblas-dev
      - liblapack-dev
before_install:
  - sudo service postgresql restart
install:
  - pip install .[test,dev,docs]
  - reentry scan
env:
  - TEST_TYPE="pre-commit" AIIDA_TEST_BACKEND=django
  - TEST_TYPE="tests" AIIDA_TEST_BACKEND=django

before_script:
  - ./.travis-data/setup_profiles.sh
script:
  - ./.travis-data/test_script.sh
