language: python
python: 2.7
cache: pip
services:
  - postgresql
addons:
  apt:
    packages:
        - gfortran
        - libblas-dev
        - liblapack-dev
install:
  - pip install -e git+https://github.com/greschd/aiida_pytest#egg=aiida_pytest
  - pip install -e .[test,dev,docs]
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
