computers:
  localhost:
    hostname: localhost
    description: localhost
    transport: local
    scheduler: direct
    work_directory: /tmp/test_aiida_wannier90_run

codes:
  wannier90:
    description: Wannier90
    default_plugin: wannier90.wannier90
    remote_computer: localhost
    remote_abspath: {wannier90_path}
